curl -i -X GET "localhost:8080/home"
echo "\n"
curl -i -X GET "localhost:8080/post/123/comment/comment_id_1"
echo "\n"
curl -i -X DELETE "localhost:8080/home"
echo "\n"
curl -i -X DELETE "localhost:8080/post/123/comment/comment_id_1"
echo "\n"
curl -i -X POST "localhost:8080/home" -d "test"
echo "\n"
curl -i -X POST "localhost:8080/post/123/comment/comment_id_1" -d "test"
echo "\n"
curl -i -X PUT "localhost:8080/home" -d "test"
echo "\n"
curl -i -X PUT "localhost:8080/post/123/comment/comment_id_1" -d "test"
echo "\n"
curl -i -X PATCH "localhost:8080/home" -d "test"
echo "\n"
curl -i -X PATCH "localhost:8080/post/123/comment/comment_id_1" -d "test"
echo "\n"
