curl -v -X GET "localhost:1069/home"
echo "\n"
curl -v -X GET "localhost:1069/post/123/comment/comment_id_1"
echo "\n"
curl -v -X DELETE "localhost:1069/home"
echo "\n"
curl -v -X DELETE "localhost:1069/post/123/comment/comment_id_1"
echo "\n"
curl -v -X POST "localhost:1069/home" -d "test"
echo "\n"
curl -v -X POST "localhost:1069/post/123/comment/comment_id_1" -d "test"
echo "\n"
curl -v -X PUT "localhost:1069/home" -d "test"
echo "\n"
curl -v -X PUT "localhost:1069/post/123/comment/comment_id_1" -d "test"
echo "\n"
curl -v -X PATCH "localhost:1069/home" -d "test"
echo "\n"
curl -v -X PATCH "localhost:1069/post/123/comment/comment_id_1" -d "test"
echo "\n"

curl -v -X POST http://localhost:1069/user -H "Content-Type: application/json" -d '{"name": "Zkrallah", "age": 21}'
echo "\n"

curl -v -X GET "localhost:1069/user?userId=1&category=teacher&limit=2"
echo "\n"
curl -v -X GET "localhost:1069/query?userId=1&category=teacher&name=zkrallah"
echo "\n"

curl -v -X GET "localhost:1069/set/header"
echo "\n"
curl -v -X GET "localhost:1069/get/header" -H "Header1: header1" -H "Header2: header2"
echo "\n"

curl -v -X GET "localhost:1069/set/status"
echo "\n"

curl -v -X GET "localhost:1069/api/v1/home"
echo "\n"
curl -v -X POST "localhost:1069/api/v1/home/123/comment/comment1"
echo "\n"

curl -v -X GET "localhost:1069/static/index.html"
echo "\n"
curl -v -X GET "localhost:1069/static/home.html"
echo "\n"
curl -O "localhost:1069/static/download.png"
echo "\n"

curl -v -X GET "localhost:1069/"
