name: Run Go Tests

on:
  pull_request:
    branches:
      - develop
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Run specific test file
        run: go test -v ./...

